version: '3.8'

services:
  manydial_service:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3003:3003'
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    command: yarn start:dev
    environment:
      PORT: 3003
    restart: always